[package]
name = "chuck"
version = "0.1.0"
authors = ["Nino Paparo"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.6", features = ["json"] }
tokio = { version = "0.2.21", features = ["full"] }
serde = { version = "1.0.114", features = ["derive"] }
